export const DRUG_CONCENTRATION_DATA = {
    "5-FU": { volPerPack: 5, dosePerPack: 250, unit: "mg", concentration: 50.00 },
    "6-MP": { volPerPack: 0, dosePerPack: 0, unit: "mg", concentration: 0.00 },
    "6-Thioguanine": { volPerPack: 0, dosePerPack: 0, unit: "mg", concentration: 0.00 },
    "Actinomycin-D": { volPerPack: 1, dosePerPack: 500, unit: "mcg", concentration: 500.00 },
    "Asparaginase": { volPerPack: 2, dosePerPack: 10000, unit: "unit", concentration: 5000.00 },
    "Bevacizumab(Avastin)": { volPerPack: 4, dosePerPack: 100, unit: "mg", concentration: 25.00 },
    "Bevacizumab": { volPerPack: 4, dosePerPack: 100, unit: "mg", concentration: 25.00 },
    "Bleomycin": { volPerPack: 5, dosePerPack: 15, unit: "mg", concentration: 3.00 },
    "Bortezomib (VELCADE)": { volPerPack: 3.5, dosePerPack: 3.5, unit: "mg", concentration: 1.00 },
    "Bortezomib": { volPerPack: 3.5, dosePerPack: 3.5, unit: "mg", concentration: 1.00 },
    "Capecitabine": { volPerPack: 0, dosePerPack: 500, unit: "mg", concentration: 0.00 },
    "Carboplatin": { volPerPack: 45, dosePerPack: 450, unit: "mg", concentration: 10.00 },
    "CCNU": { volPerPack: 0, dosePerPack: 0, unit: "mg", concentration: 0.00 },
    "Cisplatin": { volPerPack: 50, dosePerPack: 50, unit: "mg", concentration: 1.00 },
    "Cotrimoxazole": { volPerPack: 0, dosePerPack: 0, unit: "mg", concentration: 0.00 },
    "Cyclophosphamide": { volPerPack: 10, dosePerPack: 200, unit: "mg", concentration: 20.00 },
    "Cytarabine": { volPerPack: 5, dosePerPack: 100, unit: "mg", concentration: 20.00 },
    "Dexamethasone": { volPerPack: 1, dosePerPack: 4, unit: "mg", concentration: 4.00 },
    "Docetaxel": { volPerPack: 0, dosePerPack: 20, unit: "mg", concentration: 10.00 },
    "Docetaxel(Taxotere)": { volPerPack: 8, dosePerPack: 80, unit: "mg", concentration: 10.00 },
    "Doxorubicin": { volPerPack: 25, dosePerPack: 50, unit: "mg", concentration: 2.00 },
    "Doxorubicin(Lipodox)": { volPerPack: 10, dosePerPack: 20, unit: "mg", concentration: 2.00 },
    "Epirubicin": { volPerPack: 25, dosePerPack: 50, unit: "mg", concentration: 2.00 },
    "Etoposide": { volPerPack: 5, dosePerPack: 100, unit: "mg", concentration: 20.00 },
    "FLUDARABINE": { volPerPack: 2, dosePerPack: 50, unit: "mg", concentration: 25.00 },
    "Gemcitabine": { volPerPack: 25, dosePerPack: 1000, unit: "mg", concentration: 40.00 },
    "HD-Cytarabine": { volPerPack: 10, dosePerPack: 500, unit: "mg", concentration: 50.00 },
    "HD-Methotrexate": { volPerPack: 10, dosePerPack: 1000, unit: "mg", concentration: 100.00 },
    "Hydrocortisone": { volPerPack: 2, dosePerPack: 100, unit: "mg", concentration: 50.00 },
    "Idarubicin": { volPerPack: 10, dosePerPack: 10, unit: "mg", concentration: 1.00 },
    "Ifosfamide": { volPerPack: 10, dosePerPack: 1000, unit: "mg", concentration: 100.00 },
    "Irinotecan": { volPerPack: 5, dosePerPack: 100, unit: "mg", concentration: 20.00 },
    "Mesna": { volPerPack: 4, dosePerPack: 400, unit: "mg", concentration: 100.00 },
    "Methotrexate": { volPerPack: 2, dosePerPack: 50, unit: "mg", concentration: 25.00 },
    "Methylprednisolone": { volPerPack: 16, dosePerPack: 1000, unit: "mg", concentration: 62.50 },
    "Mitomycin C": { volPerPack: 20, dosePerPack: 10, unit: "mg", concentration: 0.50 },
    "Mitoxantrone": { volPerPack: 10, dosePerPack: 20, unit: "mg", concentration: 2.00 },
    "Nitrogen mustard": { volPerPack: 10, dosePerPack: 10, unit: "mg", concentration: 1.00 },
    "Oxaliplatin": { volPerPack: 10, dosePerPack: 50, unit: "mg", concentration: 5.00 },
    "Paclitaxel (Taxol)": { volPerPack: 50, dosePerPack: 300, unit: "mg", concentration: 6.00 },
    "Paclitaxel": { volPerPack: 50, dosePerPack: 300, unit: "mg", concentration: 6.00 },
    "Pamidronate disodiu": { volPerPack: 10, dosePerPack: 30, unit: "mg", concentration: 3.00 },
    "Prednisolone": { volPerPack: 0, dosePerPack: 5, unit: "mg", concentration: 0.00 },
    "Rescuvolin": { volPerPack: 5, dosePerPack: 50, unit: "mg", concentration: 10.00 },
    "Rituximab": { volPerPack: 50, dosePerPack: 500, unit: "mg", concentration: 10.00 },
    "Traztuzumab(Herce": { volPerPack: 7.143, dosePerPack: 150, unit: "mg", concentration: 21.00 },
    "Traztuzumab": { volPerPack: 7.143, dosePerPack: 150, unit: "mg", concentration: 21.00 },
    "UFT": { volPerPack: 0, dosePerPack: 0, unit: "mg", concentration: 0.00 },
    "Vinblastine": { volPerPack: 10, dosePerPack: 10, unit: "mg", concentration: 1.00 },
    "Vincristine": { volPerPack: 1, dosePerPack: 1, unit: "mg", concentration: 1.00 },
    "Zometa": { volPerPack: 5, dosePerPack: 4, unit: "mg", concentration: 0.80 }
};
