const { execSync } = require('child_process');
execSync('npm i node-forge --no-save', { stdio: 'inherit' });
const forge = require('node-forge');
const pki = forge.pki;
const keys = pki.rsa.generateKeyPair(2048);
const cert = pki.createCertificate();
cert.publicKey = keys.publicKey;
cert.serialNumber = '01';
cert.validity.notBefore = new Date();
cert.validity.notAfter = new Date();
cert.validity.notAfter.setFullYear(cert.validity.notBefore.getFullYear() + 10);
const attrs = [{ name: 'commonName', value: 'Patien System' }];
cert.setSubject(attrs);
cert.setIssuer(attrs);
cert.sign(keys.privateKey, forge.md.sha256.create());
const pemCert = pki.certificateToPem(cert);
const pemKey = pki.privateKeyToPem(keys.privateKey);
const fs = require('fs');
fs.writeFileSync('digital-certificate.txt', pemCert);
fs.writeFileSync('private-key.pem', pemKey);
console.log('Certificate generated');
